# Generated by Django 6.0.2 on 2026-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2BAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_label', models.CharField(max_length=80, verbose_name='etiqueta del dia')),
                ('title', models.CharField(max_length=200, verbose_name='actividad')),
                ('time_range', models.CharField(blank=True, max_length=80, verbose_name='horario')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Agenda B2B',
                'verbose_name_plural': 'Agenda B2B',
                'db_table': 'content_b2b_agenda_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='B2BConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, default='B2B', max_length=50, verbose_name='etiqueta')),
                ('title', models.CharField(blank=True, default='Rueda de Negocios', max_length=150, verbose_name='titulo')),
                ('description', models.TextField(blank=True, default='Mesas exclusivas para reuniones estratégicas y alianzas comerciales con compradores nacionales e internacionales.', verbose_name='descripcion')),
                ('card_title', models.CharField(blank=True, default='Inscripción B2B', max_length=120, verbose_name='titulo de la tarjeta')),
                ('price_label', models.CharField(blank=True, default='Precio regular', max_length=120, verbose_name='etiqueta de precio')),
                ('price', models.CharField(blank=True, default='S/ 1,500', max_length=60, verbose_name='precio')),
                ('price_note', models.CharField(blank=True, default='incluido IGV', max_length=120, verbose_name='nota de precio')),
                ('includes_text', models.TextField(blank=True, default='Incluye: table tent, dos sillas, WiFi, mantelería, conexión laptops, personal de logística.', verbose_name='que incluye')),
                ('cta_label', models.CharField(blank=True, default='Registrarme a la rueda', max_length=120, verbose_name='texto del boton')),
            ],
            options={
                'verbose_name': 'Configuración B2B',
                'verbose_name_plural': 'Configuración B2B',
                'db_table': 'content_b2b_config',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='imagen')),
                ('eyebrow', models.CharField(blank=True, max_length=150, verbose_name='etiqueta superior')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titulo')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtitulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'content_banner',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_headline', models.CharField(default='Trujillo, Perú', max_length=150, verbose_name='titulo de ubicacion')),
                ('location_description', models.TextField(blank=True, default='Nueva sede premium 5★ · Costa del Sol Wyndham Trujillo. Un espacio ideal para reuniones estratégicas, networking y experiencias culturales.', verbose_name='descripcion')),
                ('dates', models.CharField(blank=True, default='21, 22 y 23 de octubre 2026', max_length=150, verbose_name='fechas')),
                ('venue', models.CharField(blank=True, default='Costa del Sol Wyndham · Trujillo', max_length=200, verbose_name='sede')),
                ('guest_country', models.CharField(blank=True, default='Chile', max_length=100, verbose_name='pais invitado')),
                ('previous_edition_label', models.CharField(blank=True, default='Edición 2025', max_length=100, verbose_name='etiqueta edicion anterior')),
                ('previous_edition_stats', models.CharField(blank=True, default='+200 empresas · +380 reuniones B2B', max_length=200, verbose_name='stats edicion anterior')),
                ('map_query', models.CharField(blank=True, default='Costa del Sol Wyndham Trujillo', max_length=255, verbose_name='consulta del mapa')),
                ('contact_whatsapp_primary', models.CharField(blank=True, default='+51 931 388 602', max_length=40, verbose_name='whatsapp 1')),
                ('contact_whatsapp_secondary', models.CharField(blank=True, default='+51 993 289 550', max_length=40, verbose_name='whatsapp 2')),
                ('contact_email', models.EmailField(blank=True, default='camaradeturismolalibertad@gmail.com', max_length=254, verbose_name='email de contacto')),
                ('contact_address', models.CharField(blank=True, default='Jr. Independencia 467 · Plaza de Armas (2do piso), Trujillo', max_length=255, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Configuración del evento',
                'verbose_name_plural': 'Configuración del evento',
                'db_table': 'content_event_config',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='rol')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='cargo')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='tema en el foro')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/%Y/%m/', verbose_name='foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Disertante',
                'verbose_name_plural': 'Disertantes',
                'db_table': 'content_speaker',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('logo', models.ImageField(upload_to='sponsors/%Y/%m/', verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('tier', models.CharField(blank=True, max_length=50, verbose_name='nivel')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'db_table': 'content_sponsor',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
