# Generated by Django 6.0.2 on 2026-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='rol')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='cargo')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='tema en el foro')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/%Y/%m/', verbose_name='foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Disertante',
                'verbose_name_plural': 'Disertantes',
                'db_table': 'content_speaker',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
