# Generated by Django 6.0.2 on 2026-06-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='website',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/%Y/%m/', verbose_name='logo (archivo)'),
        ),
    ]
