# Generated by Django 6.0.2 on 2026-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_headline', models.CharField(default='Trujillo, Perú', max_length=150, verbose_name='titulo de ubicacion')),
                ('location_description', models.TextField(blank=True, default='Nueva sede premium 5★ · Costa del Sol Wyndham Trujillo. Un espacio ideal para reuniones estratégicas, networking y experiencias culturales.', verbose_name='descripcion')),
                ('dates', models.CharField(blank=True, default='21, 22 y 23 de octubre 2026', max_length=150, verbose_name='fechas')),
                ('venue', models.CharField(blank=True, default='Costa del Sol Wyndham · Trujillo', max_length=200, verbose_name='sede')),
                ('guest_country', models.CharField(blank=True, default='Chile', max_length=100, verbose_name='pais invitado')),
                ('previous_edition_label', models.CharField(blank=True, default='Edición 2025', max_length=100, verbose_name='etiqueta edicion anterior')),
                ('previous_edition_stats', models.CharField(blank=True, default='+200 empresas · +380 reuniones B2B', max_length=200, verbose_name='stats edicion anterior')),
                ('map_query', models.CharField(blank=True, default='Costa del Sol Wyndham Trujillo', max_length=255, verbose_name='consulta del mapa')),
            ],
            options={
                'verbose_name': 'Configuración del evento',
                'verbose_name_plural': 'Configuración del evento',
                'db_table': 'content_event_config',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('logo', models.ImageField(upload_to='sponsors/%Y/%m/', verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('tier', models.CharField(blank=True, max_length=50, verbose_name='nivel')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'db_table': 'content_sponsor',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
