# Generated by Django 6.0.2 on 2026-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_eventconfig_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='imagen')),
                ('eyebrow', models.CharField(blank=True, max_length=150, verbose_name='etiqueta superior')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titulo')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtitulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'content_banner',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
