# Generated by Django 6.0.2 on 2026-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_b2bconfig_b2bagendaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfig',
            name='contact_whatsapp_primary',
            field=models.CharField(blank=True, default='+51 931 388 602', max_length=40, verbose_name='whatsapp 1'),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='contact_whatsapp_secondary',
            field=models.CharField(blank=True, default='+51 993 289 550', max_length=40, verbose_name='whatsapp 2'),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='contact_email',
            field=models.EmailField(blank=True, default='camaradeturismolalibertad@gmail.com', max_length=254, verbose_name='email de contacto'),
        ),
        migrations.AddField(
            model_name='eventconfig',
            name='contact_address',
            field=models.CharField(blank=True, default='Jr. Independencia 467 · Plaza de Armas (2do piso), Trujillo', max_length=255, verbose_name='direccion'),
        ),
    ]
