# Generated by Django 6.0.2 on 2026-06-11 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stand_type_name', models.CharField(max_length=120, verbose_name='stand')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('currency', models.CharField(choices=[('PEN', 'Sol peruano (S/)'), ('USD', 'Dolar (US$)')], max_length=3, verbose_name='moneda')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pagada el')),
            ],
            options={
                'verbose_name': 'Reserva de stand',
                'verbose_name_plural': 'Reservas de stand',
                'db_table': 'stands_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('dimensions', models.CharField(blank=True, max_length=150, verbose_name='dimensiones')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('currency', models.CharField(choices=[('PEN', 'Sol peruano (S/)'), ('USD', 'Dolar (US$)')], default='PEN', max_length=3, verbose_name='moneda')),
                ('price_plus_igv', models.BooleanField(default=True, verbose_name='precio + IGV')),
                ('includes', models.TextField(blank=True, help_text='Un item por linea', verbose_name='que incluye')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Vacio = sin limite', null=True, verbose_name='cupo (stands disponibles)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Tipo de stand',
                'verbose_name_plural': 'Tipos de stand',
                'db_table': 'stands_stand_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
