# Generated by Django 6.0.2 on 2026-06-11 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='standreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_reservations', to=settings.AUTH_USER_MODEL, verbose_name='expositor'),
        ),
        migrations.AddField(
            model_name='standreservation',
            name='stand_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='stands.standtype', verbose_name='tipo de stand'),
        ),
    ]
