# Generated by Django 6.0.2 on 2026-06-08 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('expositor', 'Expositor'), ('user', 'Usuario')], db_index=True, default='user', max_length=20, verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='ExpositorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(max_length=255, verbose_name='razon social')),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC / documento')),
                ('approval_status', models.CharField(choices=[('pending', 'Pendiente de aprobacion'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=20, verbose_name='estado de aprobacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expositor_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil de expositor',
                'verbose_name_plural': 'Perfiles de expositor',
                'db_table': 'user_expositor_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
