# Generated by Django 6.0.2 on 2026-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='token QR'),
        ),
    ]
