# Generated by Django 6.0.2 on 2026-06-09 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('currency', models.CharField(choices=[('PEN', 'Sol peruano (S/)'), ('USD', 'Dolar (US$)')], default='PEN', max_length=3, verbose_name='moneda')),
                ('is_popular', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Vacio = sin limite', null=True, verbose_name='cupo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Tipo de entrada',
                'verbose_name_plural': 'Tipos de entrada',
                'db_table': 'tickets_ticket_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
