# Generated by Django 6.0.2 on 2026-06-09 15:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type_name', models.CharField(max_length=120, verbose_name='entrada')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('currency', models.CharField(choices=[('PEN', 'Sol peruano (S/)'), ('USD', 'Dolar (US$)')], max_length=3, verbose_name='moneda')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pagada el')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tickets.tickettype', verbose_name='tipo de entrada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'tickets_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
